[[plugins]]
repo='git-commit'
[[plugins]]
repo='YankRing.vim'

[[plugins]]
repo='EasyMotion'

[[plugins]]
repo='vimwiki'

[[plugins]]
repo='Rename'

[[plugins]]
repo='wincent/Command-T'

[[plugins]]
repo='jade.vim'

[[plugins]]
repo='newspaper.vim'

[[plugins]]
repo='xoria256.vim'

[[plugins]]
repo='vim-ruby/vim-ruby'

[[plugins]]
repo='kana/vim-textobj-user'

[[plugins]]
repo='kana/vim-textobj-fold'

[[plugins]]
repo='kana/vim-textobj-indent'

[[plugins]]
repo='kana/vim-textobj-lastpat'

[[plugins]]
repo='Shougo/neocomplcache'

[[plugins]]
repo='Shougo/vimfiler'

[[plugins]]
repo='h1mesuke/vim-alignta'

[[plugins]]
repo='h1mesuke/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo='Shougo/unite.vim'

[[plugins]]
repo='tsukkee/unite-help'

[[plugins]]
repo='tpope/vim-haml'

[[plugins]]
repo='tpope/vim-rails'

[[plugins]]
repo='tpope/vim-cucumber'

[[plugins]]
repo='tpope/vim-endwise'

[[plugins]]
repo='tpope/vim-surround'

[[plugins]]
repo='tpope/vim-fugitive'

[[plugins]]
repo='tpope/vim-markdown'

[[plugins]]
repo='suan/vim-instant-markdown'

[[plugins]]
repo='kchmck/vim-coffee-script'

[[plugins]]
repo='wavded/vim-stylus'

[[plugins]]
repo='nelstrom/vim-textobj-rubyblock'

[[plugins]]
repo='basyura/unite-rails'

[[plugins]]
repo='scrooloose/nerdtree'

[[plugins]]
repo='jpo/vim-railscasts-theme'

[[plugins]]
repo='elixir-lang/vim-elixir'

[[plugins]]
repo='rhysd/committia.vim'
